"""Self-contained training configuration: train_configs/learning_rate/eval1200_segmented/lr_2.5e-4.py."""

CONFIG = {'model_path': '/data16T/wjy/models/Qwen2.5-7B-Instruct',
 'bootstrap_adapter_dir': '/data16T/wjy/models/Qwen2.5-7B-Instruct/railway_lora_unsloth-adapter_best',
 'output_root': '/data16T/wjy/models/Qwen2.5-7B-Instruct',
 'experiment_name': 'qwen25_7b_data7236_lr2.5e-4_eval1200_segmented_from_base',
 'train_dataset_path': '/data16T/wjy/Learn_llm/铁路大模型/dataset_splits/traindata7236.json',
 'eval_dataset_path': '/data16T/wjy/Learn_llm/铁路大模型/dataset_splits/testdata799.json',
 'cuda_visible_devices': '2',
 'max_seq_length': 2048,
 'model_dtype': None,
 'load_in_4bit': True,
 'load_in_8bit': False,
 'full_finetuning': False,
 'local_files_only': True,
 'resume_enabled': True,
 'bootstrap_enabled': False,
 'lora_r': 32,
 'lora_alpha': 32,
 'lora_dropout': 0.0,
 'lora_bias': 'none',
 'lora_target_modules': ['q_proj',
                         'k_proj',
                         'v_proj',
                         'o_proj',
                         'gate_proj',
                         'up_proj',
                         'down_proj'],
 'use_gradient_checkpointing': 'unsloth',
 'lora_random_state': 3407,
 'use_rslora': False,
 'loftq_config': None,
 'dataset_split': 'train',
 'dataset_batched': True,
 'instruction_column': 'instruction',
 'input_column': 'input',
 'output_column': 'output',
 'eval_add_generation_prompt': True,
 'seed': 3407,
 'num_train_epochs': 2,
 'learning_rate': 2.5e-04,
 'training_max_length': 2048,
 'per_device_train_batch_size': 1,
 'gradient_accumulation_steps': 2,
 'warmup_steps': 5,
 'logging_steps': 10,
 'optim': 'adamw_8bit',
 'weight_decay': 0.01,
 'lr_scheduler_type': 'linear',
 'report_to': 'none',
 'packing': False,
 'eval_strategy': 'steps',
 'eval_steps': 600,
 'save_strategy': 'steps',
 'save_steps': 600,
 'save_total_limit': 4,
 'load_best_model_at_end': False,
 'metric_for_best_model': 'eval_bertscore_segmented_f1',
 'greater_is_better': True,
 'early_stopping_patience': 5,
 'early_stopping_min_delta': 0.0,
 'generation_max_new_tokens': 1024,
 'generation_do_sample': False,
 'generation_skip_special_tokens': True,
 'enable_bertscore': True,
 'bertscore_model_type': '/data16T/wjy/models/Bert',
 'bertscore_num_layers': 12,
 'bertscore_lang': 'zh',
 'bertscore_batch_size': 8,
 'bertscore_local_files_only': True,
 'bertscore_tokenizer_use_fast': True,
 'bertscore_skip_special_tokens': True,
 'bertscore_clean_up_tokenization_spaces': False,
 'system_column': 'system',
 'warmup_ratio': 0.0,
 'completion_only_loss': True,
 'expected_train_samples': 7236,
 'expected_eval_samples': 799,
 'expected_effective_batch_size': 2,
 'expected_optimizer_steps': 7236,
 'generation_progress_every': 10,
 'selection_eval_max_samples': 256,
 'selection_eval_seed': 3407,
 'enable_segmented_bertscore': True,
 'segmented_bertscore_chunk_tokens': 450}
